//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public static class HelperFunctions
	{
		/// <summary>
		/// Determines if a collider is solid and non-kinematic
		/// </summary>
		/// <returns><c>true</c> if can receive forces the specified collider; otherwise, <c>false</c>.</returns>
		/// <param name="collider">Collider.</param>
		public static bool CanReceiveForces(Collider collider)
		{
			return collider.attachedRigidbody != null && !collider.attachedRigidbody.isKinematic && !collider.isTrigger;
		}
	}
}

